### ISSUE TITLE
Topography.IntersectionWithPlane

### ISSUE THREAD

**Issue by josols** [CAAD-RWTH/ClockworkForDynamo#47]
I can't seem to get this node to work in daily 0.8.2? I get only null values.

**Comment by andydandy74** [comment]
This is likely due to the new IF behaviour (more info here: https://github.com/DynamoDS/Dynamo/pull/4464): I am currently not planning to fix this as I would expect that at some point there will be an IF functionality in Dynamo again that can deal with single element arguments for the ```test``` input. Plus - I don't have the time to start migrating Clockwork to Dynamo 0.8 before this fall.
Other Clockwork nodes may have similar problems: https://twitter.com/60secondrevit/status/613807436105789440

**Comment by andydandy74** [comment]
This has been fixed for the upcoming 0.8/0.9 release.
